### ISSUE TITLE
Supervisorctl_reread error when installing mailcatcher (MailCatcher doesn't start automatically)

### ISSUE THREAD

**Issue by paolooo** [puphpet/puphpet#1506]
I've got the following error when installing mailcatcher on Vagrant CentOS.
I'm on Windows 7, using vagrant v1.7.2, and Virtualbox v4.3.22

**Update: # 1**
Mailcatcher is installed correctly but it doesn't start automatically when running `vagrant up`. I still need to run the mailcatcher manually.

```
$ vagrant ssh
$ mailcatcher --http-ip=0.0.0.0
Starting MailCatcher
==> smtp://127.0.0.1:1025
==> http://0.0.0.0:1080
*** MailCatcher runs as a daemon by default. Go to the web interface to quit.
```

**Update: # 2**
I tried running --supervisord-- inside the box. It gave me the following errors. See -

```
[vagrant@localhost] $ sudo /etc/init.d/supervisord start
Starting supervisord: Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

**Update # 3 (Fixed):**

This one works for me. I did a nasty hack from alxndrmlr's comment, see ( https://github.com/puphpet/puphpet/issues/1492#issuecomment-88580664 )
except that I removed the `sudo` in `command => "curl https://bootstrap.pypa.io/ez_setup.py | sudo python",`

Here's my version:

```
# puphpet/puppet/modules/puphpet/manifests/python/pip.pp 

class puphpet::python::pip {

  Exec { path => [ '/usr/bin/', '/usr/local/bin', '/bin', '/usr/local/sbin', '/usr/sbin', '/sbin' ] }

  #  if ! defined(Package['python-setuptools']) {
  #    package { 'python-setuptools': }
  #  }
  #
  #  exec { 'easy_install pip':
  #    unless  => 'which pip',
  #    require => Package['python-setuptools'],
  #  }

  # Hack to get the latest version of setuptool
  # See https://github.com/puphpet/puphpet/issues/1492
  exec { 'install_setuptools':
    command => "curl https://bootstrap.pypa.io/ez_setup.py | python",
    cwd     => '/tmp',
    before  => Exec['easy_install pip']
  }

  exec { 'easy_install pip':
    unless  => 'which pip',
  }

  if $::osfamily == 'RedHat' {
    exec { 'rhel pip_provider_name_fix':
      command     => 'alternatives --install /usr/bin/pip-python pip-python /usr/bin/pip 1',
      subscribe   => Exec['easy_install pip'],
      unless      => 'which pip-python',
    }
  }

}
```

**Here's the error:**
```
...
Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Failed to call refresh: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
...
```

**Partial log:**

```
...
==> default: Notice: /Stage[main]/Mailcatcher::Package/Package[mailcatcher]/ensure: created
==> default: Notice: /Stage[main]/Mailcatcher::Config/User[mailcatcher]/ensure: created
==> default: Notice: /Stage[main]/Mailcatcher::Config/File[/var/log/mailcatcher]/ensure: created
==> default: Notice: /Stage[main]/Main/Supervisord::Program[mailcatcher]/File[/etc/supervisor.d/program_mailcatcher.conf]/ensure: created
==> default: Info: /Stage[main]/Main/Supervisord::Program[mailcatcher]/File[/etc/supervisor.d/program_mailcatcher.conf]: Scheduling refresh of Class[Supervisord::Reload]
==> default: Info: Class[Supervisord::Reload]: Scheduling refresh of Exec[supervisorctl_reread]
==> default: Info: Class[Supervisord::Reload]: Scheduling refresh of Exec[supervisorctl_update]
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:   File "/usr/bin/supervisorctl", line 5, in <module>
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:     from pkg_resources import load_entry_point
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:     working_set.require(__requires__)
==> default:
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:     needed = self.resolve(parse_requirements(requirements))
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns:     raise DistributionNotFound(req)
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]/returns: pkg_resources.DistributionNotFound: meld3>=0.6.5
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Failed to call refresh: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:   File "/usr/bin/supervisorctl", line 5, in <module>
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:     from pkg_resources import load_entry_point
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:     working_set.require(__requires__)
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:     needed = self.resolve(parse_requirements(requirements))
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
==> default:
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns:     raise DistributionNotFound(req)
==> default: Notice: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]/returns: pkg_resources.DistributionNotFound: meld3>=0.6.5
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: Failed to call refresh: /usr/bin/supervisorctl update returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_update]: /usr/bin/supervisorctl update returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Module[soap]/Php::Module[soap]/Package[PhpModule_soap]/ensure: created
==> default:
==> default: Info: /Stage[main]/Main/Puphpet::Php::Module[soap]/Php::Module[soap]/Package[PhpModule_soap]: Scheduling refresh of Service[php-fpm]
==> default: Notice: /Stage[main]/Main/Service[php-fpm]/ensure: ensure changed 'stopped' to 'running'
==> default: Info: /Stage[main]/Main/Service[php-fpm]: Unscheduling refresh on Service[php-fpm]
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 2457.48 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**My config.yml**
```
---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                YbDnxJi1smEk:
                    host: '9412'
                    guest: '22'
                etet1:
                    host: '8082'
                    guest: '80'
                etet2:
                    host: '1080'
                    guest: '1080'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            EU0lMlU57kBr:
                owner: www-data
                group: www-data
                source: ./www
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        tydhlimhnovw:
            servername: ninopaolo.lcl
            serveraliases:
                - www.ninopaolo.lcl
            docroot: /var/www/ninopaolo.com
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            directories:
                hss5zpzv5equ:
                    provider: directory
                    path: /var/www/ninopaolo.com
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        mweek238y2pq:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: 0
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        msqfuggmvdch:
            proxy: ''
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            locations:
                4gtpijbntozl:
                    location: /
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                4qy3rgfxrkn1:
                    location: '~ \.php$'
                    try_files:
                        - $uri
                        - $uri/
                        - index.php
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
php:
    install: '1'
    settings:
        version: '55'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - mbstring
            - bcmath
            - common
            - dba
            - enchant
            - fpm
            - gd
            - gmp
            - ldap
            - imap
            - mssql
            - odbc
            - pgsql
            - pdo
            - pspell
            - recode
            - snmp
            - soap
            - tidy
            - xmlrpc
        pear: {  }
        pecl:
            - apc
            - Fileinfo
            - gearman
            - igbinary
            - imagick
            - memcache
            - memcached
            - oauth
            - pecl_http
            - pthreads
            - propro
            - raphf
            - SPL_Types
            - uploadprogress
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        html_errors: On
        short_open_tag: On
        max_execution_time: '360'
        post_max_size: 100M
        upload_max_filesize: 100M
        max_input_vars: '10000'
        memory_limit: 2048M
        sendmail_path: '/usr/bin/env catchmail -f admin@localhost.com'
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
mysql:
    install: '0'
    settings:
        version: '5.6'
        root_password: 'spike'
        override_options: {  }
    adminer: '1'
    users:
        w5Ef5dclqrn8:
            name: dbuser
            password: 'spike'
    databases:
        rO21WWuEMzdI:
            name: dbname
            sql: ''
    grants:
        NPUnseAAUqYL:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
percona:
    install: '1'
    install_server: '1'
    version: '5.6'
    root_password: 'spike'
    adminer: '1'
    databases:
        ninopaolo:
            grant:
                - ALL
            name: ninopaolo
            host: localhost
            user: paolo
            password: 'spike'
            sql_file: /var/www/ninopaolo.com/schema/db.sql
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: 'spike'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
        log_path: /var/log/mailcatcher/mailcatcher.log
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by adamlundrigan** [comment]
I just hit this as well, but with Ubuntu 12.04 LTS.  Fixed it by adding `python-meld3` to the list of packages to install.

**Comment by adamlundrigan** [comment]
Also appears to be a duplicate of #1492

**Comment by paolooo** [comment]
Thanks for the quick reply @adamlundrigan, but I think it's not a duplicate. My error is not about dependency.

```
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: Failed to call refresh: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Supervisord::Reload/Exec[supervisorctl_reread]: /usr/bin/supervisorctl reread returned 1 instead of one of [0]
```

**Comment by Zeromax** [comment]
@paolooo I had the same error and fixed it with https://github.com/puphpet/puphpet/issues/1492#issuecomment-88580664

**Comment by paolooo** [comment]
Thanks @Zeromax and @adamlundrigan for the help. Yeah! It did fixed the problem.
