### ISSUE TITLE
Error on vagrant up. 

### ISSUE THREAD

**Issue by jhaveDK** [puphpet/puphpet#1512]
Hi, 

I try to setup this vagrant image, but its give some errors. I cant find any information about what going wrong :(  

```
==> default: Info: /Stage[main]/Main/Puphpet::Php::Module[mysqlnd]/Php::Module[mysqlnd]/Package[PhpModule_mysqlnd]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]/ensure: ensure changed 'purged' to 'present'
==> default: Info: /Stage[main]/Main/Puphpet::Php::Module[curl]/Php::Module[curl]/Package[PhpModule_curl]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Module[gd]/Php::Module[gd]/Package[PhpModule_gd]/ensure: ensure changed 'purged' to 'present'
==> default: Info: /Stage[main]/Main/Puphpet::Php::Module[gd]/Php::Module[gd]/Package[PhpModule_gd]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Main/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]/ensure: ensure changed 'purged' to 'present'
==> default:
==> default: Info: /Stage[main]/Main/Puphpet::Php::Module[intl]/Php::Module[intl]/Package[PhpModule_intl]: Scheduling refresh of Service[php5-fpm]
==> default: Notice: /Stage[main]/Main/Service[php5-fpm]: Triggered 'refresh' from 19 events
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 184.69 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

```bash
---
vagrantfile-local:
    vm:
        box: puphpet/ubuntu1204-x64
        box_url: puphpet/ubuntu1204-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                fYGQsS1ebuCa:
                    host: '7378'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            SDra9ZHLrnR2:
                owner: www-data
                group: www-data
                source: ./www/
                target: /var/www
                sync_type: default
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        f6e7c4hkshvd:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            directories:
                728s7g8hdsl0:
                    provider: directory
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts: {  }
php:
    install: '1'
    settings:
        version: '54'
    fpm_settings:
        port: 9000
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - curl
            - gd
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.17.1
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        MV4VFAbosNlw:
            version: ''
nodejs:
    install: '0'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        zZlrZKw6FQOH:
            version: ''
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: 
            mysqld:
                 sql_mode: 'STRICT_ALL_TABLES,ONLY_FULL_GROUP_BY,NO_ZERO_DATE'
    adminer: 0
    users: {  }
    databases:
        BspQOJqMgGYp:
            name: database
            sql: /var/www/sql/database.sql
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: ''
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

**Comment by kasylozy** [comment]
I have the same problem

**Comment by erdemece** [comment]
Can you start virtualbox and then do vagrant up? 

That way you may receive an error.

**Comment by dohernandez** [comment]
I'm having the same problem!! I'll try many things and many times and always is throwing the same error in the same place.
Did anyone find the solution?

**Comment by jhaveDK** [comment]
Yes i can start the virtualbox and connect to it. But ngnix and PHP-fpm is not started.

**Comment by artisaninweb** [comment]
Having the same problem!

**Comment by jhaveDK** [comment]
I have tried to search for the problem by 
- downloading a standard package  of puphpet, but it gives the same result. 
- I've tried to run it on two different machines but with the same result.
- Check my Vagrant and virtualbox install. 

Is this a general bug, its look like its come when the new puphpet version comes out.

**Comment by artisaninweb** [comment]
A workaround is to `vagrant provision` after the error is shown on a `vagrant up`.

**Comment by erdemece** [comment]
mate you have to look for an error.

when you vagrant up it does not give you any error.

just ssh into the server and try to start nginx and see what error you receive then we can go from there.

**Comment by jhaveDK** [comment]
Erdemece i know, but where 

If i look in the stage file /var/lib/puppet/state/state.yaml give this output, its stop in with PHP-FPM.  

```
"Php::Augeas[XDEBUG/xdebug.remote_handler-dbgp]":
    !ruby/sym checked: 2015-04-10 21:38:29.574505 +00:00
  Augeas[php_ini-XDEBUG/xdebug.remote_handler-dbgp]:
    !ruby/sym checked: 2015-04-10 21:38:29.523070 +00:00
    !ruby/sym synced: 2015-04-10 21:38:29.529907 +00:00
  Package[php5-dev]:
    !ruby/sym checked: 2015-04-10 21:38:29.900352 +00:00
    !ruby/sym synced: 2015-04-10 21:38:34.375114 +00:00
  "Php::Module[mcrypt]":
    !ruby/sym checked: 2015-04-10 21:38:57.226328 +00:00
  Exec[pecl-pecl_http]:
    !ruby/sym checked: 2015-04-10 21:38:34.644492 +00:00
    !ruby/sym synced: 2015-04-10 21:38:54.454348 +00:00
  "Php::Module[fpm]":
    !ruby/sym checked: 2015-04-10 21:39:10.543033 +00:00
  Package[PhpModule_mcrypt]:
    !ruby/sym checked: 2015-04-10 21:38:54.613229 +00:00
    !ruby/sym synced: 2015-04-10 21:38:57.171559 +00:00
  "Php::Module[mysqlnd]":
    !ruby/sym checked: 2015-04-10 21:39:00.995437 +00:00
  Package[PhpModule_mysqlnd]:
    !ruby/sym checked: 2015-04-10 21:38:57.474064 +00:00
    !ruby/sym synced: 2015-04-10 21:39:00.948456 +00:00
  "Php::Module[cli]":
    !ruby/sym checked: 2015-04-10 21:39:01.157656 +00:00
  "Php::Module[gd]":
    !ruby/sym checked: 2015-04-10 21:39:05.566354 +00:00
  Package[PhpModule_gd]:
    !ruby/sym checked: 2015-04-10 21:39:01.331417 +00:00
    !ruby/sym synced: 2015-04-10 21:39:05.506736 +00:00
  "Php::Module[intl]":
    !ruby/sym checked: 2015-04-10 21:39:10.275858 +00:00
  Package[PhpModule_intl]:
    !ruby/sym checked: 2015-04-10 21:39:05.751035 +00:00
    !ruby/sym synced: 2015-04-10 21:39:10.225686 +00:00
  Service[php5-fpm]:
    !ruby/sym checked: 2015-04-10 21:39:10.337136 +00:00
```

**Comment by jhaveDK** [comment]
I have try to take a look on and it look likes its missing some packages. 

```
[05:08 PM]-[root@main]-[~]
# service supervisord restart
Restarting supervisor: Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

**Comment by mimopo** [comment]
@jhaveDK I have exactly the same problem

**Comment by mimopo** [comment]
Not solved yet, but you can try to install the python-meld3 package (it solves the supervisord issue).

**Comment by mgarciadelojo** [comment]
Same here. This annoying error is making me crazy. Tried thousand times with different puphpet options: os, php/nginx, databases, etc...

**Comment by shivapoudel** [comment]
@jtreminio nginx and php5-fpm won't start?

PHP files are download :worried:

**Comment by shivapoudel** [comment]
Also for apache

**Comment by mimopo** [comment]
The "The SSH command responded..." error is still there, but It seems that I got the machine working.
Try enabling  "proxy_fcgi" and "proxy" apache modules and adding a "FilesMatch Block":
```
            directories:
                oiyyiionbujc:
                    provider: directory
                    path: /var/www/project/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        wuraek6ulkdg:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
```

**Comment by mgarciadelojo** [comment]
But, did you get php working? In my environment, I can do `vagrant ssh` but apache doesn't work.

**Comment by mimopo** [comment]
Yes, apache and PHP are working, but the error message is still there.

**Comment by mgarciadelojo** [comment]
Ok, I'll let you know when I try it. Thanks!!

**Comment by mgarciadelojo** [comment]
@mimopo Tried! It works but I don't like this errors...

```
==> default: Error: Operation not permitted - /var/www/html/index.html20150415-8991-18c0p0h
==> default: 
==> default: Error: /Stage[main]/Main/File[/var/www/html/index.html]/content: change from {md5}74cec59a19e5d16f7cc6a2445e35fa3b to {md5}85a571ae4985a6c6b49dadaac8f3a54d failed: Operation not permitted - /var/www/html/index.html20150415-8991-18c0p0h
==> default: Notice: /Stage[main]/Main/File[/var/www/html/index.html]/owner: owner changed 'www-data' to 'root'
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 198.42 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jhaveDK** [comment]
Its look like its a access problem with the www folder.

**Comment by jtreminio** [comment]
Not one of you has pasted the actual error.

**Comment by artisaninweb** [comment]
Still getting the error, is there a fix already? @jtreminio if you can tell me how to find out the error i will post it here. I can't figure out the problem.

**Comment by jtreminio** [comment]
@artisaninweb doing this in #1540

It's a problem with your host's permissions being too strict, the vm can't write to it.

**Comment by jkenneydaniel** [comment]
@mgarciadelojo @artisaninweb 

Looks like I got this working!

Modifying the Vagrantfile-local and appending

```
, mount_options: ['dmode=775', 'fmode=774']
```

to the end of all

```
config.vm.synced_folder
```

calls allows for everything to run smoothly.

You may want to adjust the permissions to your liking but it seems to resolve the issue.

**Comment by mgarciadelojo** [comment]
It sounds good. Thank you for the tip!

2015-04-23 8:31 GMT+02:00 Daniel Joseph Kenney JR <notifications@github.com>
:

**Comment by jkenneydaniel** [comment]
It actually may not work! I’m trying something else now to see if I am close. Lol.

—————————————————
Sincerely,
Daniel Kenney

Mobile: 561-758-3793
Work: 561-544-6006 x205

           <http://magento.stackexchange.com/users/2815/daniel>           <https://github.com/jkenneydaniel> <http://www.magentocommerce.com/certification/directory/dev/561783/>
 <http://www.magentocommerce.com/certification/directory/dev/561783/>

**Comment by artisaninweb** [comment]
@jtreminio me and all my co-workers are having the same problem without changing anything on our machines.. it's still a problem.

**Comment by artisaninweb** [comment]
I Just added `, mount_options: ['dmode=755', 'fmode=774']` after every `config.vm.synced_folder` and that didn't change anything.

**Comment by mgarciadelojo** [comment]
Did you make a `vagrant provision` after `vagrant up`?

2015-04-23 9:50 GMT+02:00 artisaninweb <notifications@github.com>:

**Comment by artisaninweb** [comment]
Yes that's the work-around, but it's not the real problem.
On `vagrant up` the error still shows.

**Comment by jkenneydaniel** [comment]
I reconfigured my puphpet to use NFS when mounting the shared folder and it seems to worked - try that and see if it still happens?

**Comment by Zakariya90** [comment]
If you use shell scripting file make sure to use the option -y to assume yes to all queries and do not prompt. Ex, sudo apt-get -y install vim

Hope this might help someone else.

**Comment by BallisticPain** [comment]
So it seems that the solution here is to go generate a new puppet config to match the new criteria? I'm already using NFS.

I wish the error were actually descriptive. My error didn't happen until ALL of my dependencies were installed so my box was up and working. I did have to do a `vagrant provision` to get all my extra scripts executed.

Thanks,
Jarvis

**Comment by slakbal** [comment]
Hi 

I think I found the error on this....

in the Homestead.yaml file this is the default:

folders:
    - map: ~/code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public

**Note** the word "Code". If you for example remove the "code" path or change it, this error occurs. But if you leave all your sites relative to this folder it works.

e.g.

folders:
    - map: ~/code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public 

    - map: myapp.app
      to: /home/vagrant/Code/myapp/public

**Comment by dusanPerisic** [comment]
Hi guys, in my case problem is in puphpet configuration file config.yaml in the next lines (that is default puphpet configuration):
`ssl_cert: LETSENCRYPT`
`ssl_key: LETSENCRYPT `
`ssl_chain: LETSENCRYPT `
`ssl_certs_dir: LETSENCRYPT`
I just change to:
`ssl_cert: ''`
`ssl_key: ''`
`ssl_chain: ''`
`ssl_certs_dir: ''`

After that for me everithing is good :dancing_men:

**Comment by duxor** [comment]
Hi guys, in my case problem is in puphpet configuration file config.yaml in the next lines (that is default puphpet configuration):

> ssl_cert: LETSENCRYPT
> ssl_key: LETSENCRYPT
> ssl_chain: LETSENCRYPT
> ssl_certs_dir: LETSENCRYPT

I just change to:

> ssl_cert: ''
> ssl_key: ''
> ssl_chain: ''
> ssl_certs_dir: ''

After that for me everithing is good :dancing_men:
