### ISSUE TITLE
ruby gems error

### ISSUE THREAD

**Issue by cdepner** [puphpet/puphpet#1626]
I have a few problems with my Debian. If I install ruby and gems with the configfile:(http://pastebin.com/SBWb1hgS) I get the following error message when you run `sudo /usr/bin/ruby /usr/bin/compass`
```
Error Output:
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- compass (LoadError)
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/compass:20:in `block in <main>'
	from /usr/bin/compass:8:in `fallback_load_path'
	from /usr/bin/compass:19:in `<main>'
```

If I manually install it like this:
```
gem install compass --no-rdoc --no-ri
gem install css_parser --no-rdoc --no-ri
sudo ln -s /usr/local/rvm/gems/ruby-1.9.3-p551/wrappers/ruby /usr/bin/ruby
sudo ln -s /usr/local/rvm/gems/ruby-1.9.3-p551/gems/compass-1.0.3/bin/compass /usr/bin/compass
```
It will works. Is there a reason for this or do I have to install it via scripts?

**Comment by jtreminio** [comment]
The way Ruby and RVM is managed has changed recently. I do not believe this issue to be valid any longer.
