### ISSUE TITLE
Issue with vagrant up - undefined method `color?'

### ISSUE THREAD

**Issue by Fynkymynky** [puphpet/puphpet#2031]
I've upgraded my Virtualbox with `vagrant box update` but when I run `vagrant up`

But it soon crashes and throws this error.

`puphpet/ruby/puppet.rb:195:in `run_puppet_apply': undefined method `color?' for #<Vagrant::UI::Colored:0x00000102128b28> (NoMethodError)`

Any idea what this error is and how to fix it?

Thanks

**Comment by Fynkymynky** [comment]
I I comment out the line

`
            if !@machine.env.ui.color?
            options << "--color=false"
            end
`

I get a new error

`puphpet/ruby/puppet.rb:226:in `join': can't convert Vagrant::Config::V2::DummyConfig to String (Vagrant::Config::V2::DummyConfig#to_str gives Vagrant::Config::V2::DummyConfig) (TypeError)`

**Comment by Fynkymynky** [comment]
I reinstalled virtual box and vagrant again, both latest versions.

This resulted in vagrant not being found. Deleted all instances of .vagrant files and symlinked vagrant again

`sudo ln -s /opt/vagrant/bin/vagrant /usr//bin/vagrant`

Ran `vagrant up` seems to be working now.
