### ISSUE TITLE
Error downloading ez_setup.py

### ISSUE THREAD

**Issue by paulbunyannet** [puphpet/puphpet#2283]
I'm getting an error when trying to pull in https://bootstrap.pypa.io/ez_setup.py and https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py. Here's my config https://dpaste.de/SGmn I don't know what these two tools do to cause this error.

    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: --2016-04-25 15:59:27--  https://bootstrap.pypa.io/ez_setup.py
    ==> machine1: 
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Resolving bootstrap.pypa.io... 23.235.40.175
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Connecting to bootstrap.pypa.io|23.235.40.175|:443... connected.
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: HTTP request sent, awaiting response... 200 OK
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Length: 12059 (12K) [text/x-python]
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Saving to: “/.puphpet-stuff/ez_setup.py”
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:      0K .......... .                                          100% 1.03G=0s
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: 2016-04-25 15:59:27 (1.03 GB/s) - “/.puphpet-stuff/ez_setup.py” saved [12059/12059]
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Extracting in /tmp/tmpQZTh_t
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: Traceback (most recent call last):
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/.puphpet-stuff/ez_setup.py", line 415, in <module>
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     sys.exit(main())
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/.puphpet-stuff/ez_setup.py", line 412, in main
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     return _install(archive, _build_install_args(options))
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/.puphpet-stuff/ez_setup.py", line 52, in _install
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install  ez_setup]/returns:     with archive_context(archive_filename):
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     return self.gen.next()
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/.puphpet-stuff/ez_setup.py", line 103, in archive_context
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     with ContextualZipFile(filename) as archive:
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 696, in __init__
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     self._GetContents()
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 716, in _GetContents
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     self._RealGetContents()
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 728, in _RealGetContents
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns:     raise BadZipfile, "File is not a zip file" 
    ==> machine1: Notice: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: zipfile.BadZipfile: File is not a zip file
    ==> machine1: Error: wget https://bootstrap.pypa.io/ez_setup.py -O /.puphpet-stuff/ez_setup.py &&                 python /.puphpet-stuff/ez_setup.py returned 1 instead of one of [0]
    ==> machine1: Error: /Stage[main]/Puphpet::Python::Pip/Exec[Download and install ez_setup]/returns: change from notrun to 0 failed: wget https://bootstrap.pypa.io/ez_setup.py -O /.puphpet-stuff/ez_setup.py &&                 python /.puphpet-stuff/ez_setup.py returned 1 instead of one of [0]

    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    ==> machine1:
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:                                  Dload  Upload   Total   Spent    Left  Speed
    100 12059  100 12059    0     0  38522      0 --:--:-- --:--:-- --:--:--  301keturns:
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns: Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns: Extracting in /tmp/tmpwrcARx
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns: Traceback (most recent call last):
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "<stdin>", line 415, in <module>
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "<stdin>", line 412, in main
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "<stdin>", line 52, in _install
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:     return self.gen.next()
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "<stdin>", line 103, in archive_context
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 696, in __init__
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:     self._GetContents()
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 716, in _GetContents
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:     self._RealGetContents()
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:   File "/usr/lib64/python2.6/zipfile.py", line 728, in _RealGetContents
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns:     raise BadZipfile, "File is not a zip file"
    ==> machine1: Notice: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns: zipfile.BadZipfile: File is not a zip file
    ==> machine1: Error: curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python returned 1 instead of one of [0]
    ==> machine1: Error: /Stage[main]/Supervisord::Pip/Exec[install_setuptools]/returns: change from notrun to 0 failed: curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python returned 1 instead of one of [0]

**Comment by paulbunyannet** [comment]
Found at least one issue, a downloaded source returned a 404:

    ⇒  wget https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
    --2016-04-25 11:12:21--  https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
    Resolving pypi.python.org... 23.235.40.223
    Connecting to pypi.python.org|23.235.40.223|:443... connected.
    HTTP request sent, awaiting response...
      HTTP/1.1 404 Not Found
      Content-Type: application/xml
      Server: AmazonS3
      Via: 1.1 varnish
      Fastly-Debug-Digest: a9b660283fda0ad56ad316e97657527d77e6c4148a6c44cf9d5321636cfb773c
      Cache-Control: max-age=60, public
      Content-Length: 313
      Accept-Ranges: bytes
      Date: Mon, 25 Apr 2016 16:12:22 GMT
      Via: 1.1 varnish
      Age: 26
      Connection: keep-alive
      X-Served-By: cache-sea1920-SEA, cache-ord1734-ORD
      X-Cache: HIT, MISS
      X-Cache-Hits: 1, 0
      X-Timer: S1461600742.111688,VS0,VE53
      X-Frame-Options: deny
      X-XSS-Protection: 1; mode=block
      X-Content-Type-Options: nosniff
      X-Permitted-Cross-Domain-Policies: none
    2016-04-25 11:12:22 ERROR 404: Not Found.

**Comment by paulbunyannet** [comment]
Looks like it was python, turning off the install of python in the config.yaml let vagrant up go all the way through.
