### ISSUE TITLE
deprecated is_ validation methods

### ISSUE THREAD

**Issue by dekar91** [puphpet/puphpet#2542]
Hi!

Some validation methods are deprecated in new version of stdlib.
Because of if we will see follow in our console:
```
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 14]:
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 5]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 5]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 5]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 5]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Numeric. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 5]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Bool instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 6]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 16]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/server.pp", 6]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 60]:["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/nginx/install.pp", 52]
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
==> sintapp: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 68]:
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
```

I tried to change this line:
`    if is_string($rule['port']) {`
to this:
`    if validate_legacy(Stdlib::Compat::String, "is_string", $rule['port']) {`
In file puphpet/puppet/modules/puphpet/manifests/firewall.pp

But now I see following:
```
Warning: validate_legacy(is_string) expected a String value, got Tuple at ["/tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/puphpet/manifests/init.pp", 13]:
==> sintapp:    (at /tmp/vagrant-puppet/modules-6efb28676d1d52f85264398a171b526b/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
```

What wrong with it ?

**Comment by jtreminio** [comment]
The latest supported version of stdlib is 4.12.0. I cannot offer support for anything else.
